# Generated by Django 3.0.4 on 2021-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanboard', '0003_auto_20210410_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
